apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-and-cleanup
spec:
  steps:
    - name: test
      image: python:3.9
      script: |
        python3 -m unittest

    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning up..."
